environment:
  matrix:
    - nodejs_version: '4'
    - nodejs_version: '5'
install:
  - ps: Install-Product node $env:nodejs_version
  - set CI=true
  - npm -g install npm@latest
  - set PATH=%APPDATA%\npm;%PATH%
  - set NODE_ENV=test
  - npm install
matrix:
  fast_finish: true
build: off
version: '{build}'
shallow_clone: true
clone_depth: 1
test_script:
  - node --version
  - npm --version
  - .\node_modules\.bin\eslint .
  - .\node_modules\.bin\mocha --timeout 5000 test/index.js --no-exit
